schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "batch_render_actions"
version = "1.0.0"
name = "Batch Render Actions"
tagline = "Render each animation action to its own folder"
maintainer = "Pádraig Ó Cinnéide"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Animation", "Render"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
